### ISSUE TITLE
Wat als bedragTxtBox.Text een ongeldige waarde bevat?

### ISSUE THREAD

**Issue by timschlechter** [GithubDuke/MonopolyMunteenheden#4]
https://github.com/GithubDuke/MonopolyMunteenheden/blob/d4e38e4c124aaafca712ee63efbc6e42135cdab8/MonopolyMunteenheden/MainWindow.xaml.cs#L61

`int.TryParse` geeft een boolean terug: `true` als het gelukt is, `false` als de input string een ongeldige waarde heeft (bijvoorbeeld tekst ipv een getal)

Wat moet er gebeuren als de invoer ongeldig is? Momenteel gaat je programma gewoon door, en zal `bedrag` waarschijnlijk `0` zijn.

**Comment by dukesteen** [comment]
Klopt, bedrag is dan 0. Maar dit hoort zo, ik zou ook kunnen break;'en
